name: treelights
description: 3d version of matt parker's tree
# version: 1.0.0
homepage: https://treelights.vercel.app/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
#  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
